Resources:
  allowedIP:
    Type: AWS::WAF::IPSet
    Properties:
      Name: iptoallow
      IPSetDescriptors:
        - Type: IPV4
          Value: 213.251.23.187/32

  stringRegexMatch:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: stringmatch
      ByteMatchTuples:
        - FieldToMatch:
            Type: URI
          TargetString: wp-admin
          TextTransformation: URL_DECODE
          PositionalConstraint: CONTAINS

  wafRule:
    Type: AWS::WAF::Rule
    Properties:
      Name: wpadminlockdown
      MetricName: wpadminlockdown
      Predicates:
        - DataId: !Ref allowedIP
          Negated: false
          Type: IPMatch
        - DataId: !Ref stringRegexMatch
          Negated: false
          Type: ByteMatch


  wafACL:
    Type: AWS::WAF::WebACL
    Properties:
      Name: Web ACL with a rule for IP and string regex.
      DefaultAction:
        Type: BLOCK
      MetricName: mywebacl
      Rules:
        - Action:
            Type: ALLOW
          Priority: 1
          RuleId: !Ref wafRule


  wafAssociatealb:
    Type: AWS::WAFRegional::WebACLAssociation
    Properties:
      ResourceArn: arn:aws:elasticloadbalancing:eu-west-1:721956817211:loadbalancer/app/jsarc-wordpress/5c06ed0149d5b2cc
      WebACLId: !Ref wafACL
