pipeline:

  build-image:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t jsarc-wordpress .
    when:
      branch: plugins_test
      event: push

  push_to_quay:
    image: docker:18.03
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+jsarc" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag jsarc-wordpress quay.io/ukhomeofficedigital/osct-jsarc:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/osct-jsarc:$${DRONE_COMMIT_SHA}
    when:
      branch: plugins_test
      event: push

  deploy_to_kube:
    image: quay.io/ukhomeofficedigital/kd:v1.10.6
    secrets:
      - kube_token_acp_notprod
    environment:
      - IMAGE_URL=quay.io/ukhomeofficedigital/osct-jsarc:${DRONE_COMMIT_SHA}
      - DRONE_DEPLOY_TO=acp-notprod
    commands:
      - apk update
      - apk add curl
      - chmod +x bin/deploy.sh
      - bin/deploy.sh
    when:
      branch: master
      event: push
