---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build-wordpress-image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    # wait for docker service to come up
    - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
    - docker build -t docker.digital.homeoffice.gov.uk/osct-jsarc:$${DRONE_BUILD_NUMBER} .
  volumes:
    - name: dockersock
      path: /var/run
  when:
    event:
      - pull_request
      - push

- name: Scan-Wordpress-Image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  pull: always
  failure: ignore
  environment:
    IMAGE_NAME: docker.digital.homeoffice.gov.uk/osct-jsarc:${DRONE_BUILD_NUMBER}
    SEVERITY: HIGH,CRITICAL
  when:
    event:
    - pull_request
    - push
  depends_on:
  - build-wordpress-image

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
name: Maintenance-Image-Vulnerability-Scan
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_wordpress_ecr
  pull: if-not-exists
  image: plugins/ecr
  environment:
    AWS_REGION: eu-west-2
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: jsarc/default
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    dockerfile: ./Dockerfile
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
  when:
    branch:
      - master
      - feature/*
    event:
      - push

- name: scan_maintenance_image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  pull: always
  failure: ignore
  environment:
    IMAGE_NAME: docker.digital.homeoffice.gov.uk/osct-jsarc:${DRONE_BUILD_NUMBER}
    SEVERITY: HIGH,CRITICAL
  when:
    event:
    - pull_request
    - push
  depends_on:
  - build_wordpress_ecr

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
name: deploy-notprod
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: deploy_wordpress_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - apk update
    - apk add curl
    - bin/deploy.sh
  environment:
    IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/jsarc/default:${DRONE_COMMIT_SHA}
    DRONE_DEPLOY_TO_ACP: acp-notprod
    KUBE_TOKEN_ACP_NOTPROD:
      from_secret: kube_token_acp_notprod
  when:
    branch:
      - master
    event:
      - push

- name: manual_deploy_wordpress_to_prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - apk update
    - apk add curl
    - bin/deploy.sh
  environment:
    IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/jsarc/default:${DRONE_COMMIT_SHA}
    DRONE_DEPLOY_TO_ACP: acp-prod
    KUBE_NAMESPACE: jsarc
    KUBE_TOKEN_ACP_PROD:
      from_secret: KUBE_TOKEN_ACP_PROD
  when:
    event:
      - promote

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: SonarQube Scan

platform:
  os: linux
  arch: amd64

steps:
- name: sonarqube_core_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner:latest

trigger:
  event:
    - push
    - pull_request
    - promote
