version: '3'
services:
  wordpress:
    depends_on:
    - database
    #image: 721956817211.dkr.ecr.eu-west-1.amazonaws.com/jsarcwordpress:191
    build: .
#    volumes:
#    - ./website-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: jsarc #for demo purposes only otherwise this is called from an environment file
      WORDPRESS_DB_USER: jsarc
      WORDPRESS_DB_NAME: jsarc
    ports:
    - 80:80
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: demopassword #for demo purposes only otherwise this is called from an environment file
      MYSQL_DATABASE: jsarc
      MYSQL_USER: jsarc
      MYSQL_PASSWORD: jsarc
    ports:
    - 3306:3306
#  phpmyadmin:
#    depends_on:
#    - database
#    image: phpmyadmin/phpmyadmin
#    ports:
#    - 8080:80
#    environment:
#      PMA_HOST: database
#      MYSQL_ROOT_PASSWORD: demopassword #for demo purposes only otherwise this called from an environment file