version: '3'
services:
  wordpress:
    container_name: JSARC
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: jsarc #for demo purposes only otherwise this is called from an environment file
      WORDPRESS_DB_USER: jsarc
      WORDPRESS_DB_NAME: jsarc
      WORDPRESS_DEBUG: 0
      SITE_URL: 'http://localhost:8081'
      SITE_TITLE: JSaRC
      ADMIN_USER: test
      ADMIN_EMAIL: test@example.com
      ADMIN_PASSWORD: test1234
      DEV_DEPLOYMENT: 'yes'
    ports:
      - 8081:8081
    volumes:
      - ./website-content/themes/jsarc:/var/www/jsarc
    networks:
      - app-network
  database:
    image: mariadb:10.6
    container_name: JSARC-DB
    environment:
      MYSQL_ROOT_PASSWORD: demopassword #for demo purposes only otherwise this is called from an environment file
      MYSQL_DATABASE: jsarc
      MYSQL_USER: jsarc
      MYSQL_PASSWORD: jsarc
    ports:
      - "3406:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./tmp:/docker-entrypoint-initdb.d
    networks:
      - app-network
volumes:
  mysql:
networks:
  app-network:
    driver: bridge
