---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jsarc-admin
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    stable.k8s.psg.io/kcm.provider: "http"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx-external"
#    ingress.kubernetes.io/whitelist-source-range: |
#      62.25.109.196/32,
#      80.193.85.91/32,
#      52.48.127.150/31,
#      52.48.127.152/31,
#      52.209.62.128/25,
#      213.251.23.164
#      213.251.23.185
#      213.251.23.186
#      213.251.23.187
spec:
  tls:
    - hosts:
        - {{ .ADMIN_SITE_URL }}
      secretName: jsarcadmin
  rules:
    - host: {{ .ADMIN_SITE_URL }}
      http:
        paths:
          - backend:
              serviceName: jsarc-admin
              servicePort: 8080
            path: /
