---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jsarc-admin
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTP"
    ingress.kubernetes.io/proxy-body-size: "8m"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/whitelist-source-range: |
      62.25.109.196/32,
      52.48.127.144/28,
      52.209.62.128/25,
      52.56.62.128/25
spec:
  tls:
    - hosts:
        - {{ .ADMIN_SITE_URL }}
      secretName: jsarcadmin-cmio
  rules:
    - host: {{ .ADMIN_SITE_URL }}
      http:
        paths:
          - backend:
              serviceName: jsarc-admin
              servicePort: 8080
            path: /
