---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jsarc-prod
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx-external"
spec:
  tls:
    - hosts:
        - {{ .PROD_URL }}
      secretName: jsarcprod-cmio
  rules:
    - host: {{ .PROD_URL }}
      http:
        paths:
          - backend:
              serviceName: jsarc
              servicePort: 8080
            path: /

