---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .JSARC_NAME }}
spec:
  replicas: {{ .REPLICA_COUNT }}
  template:
    metadata:
      labels:
        name: {{ .JSARC_NAME }}
        role: wordpress
    spec:
      securityContext:
        runAsUser: 33
      containers:
        - name: jsarc-wordpress
          image: {{ .IMAGE_URL }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /robots.txt
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 4
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /robots.txt
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 4
            successThreshold: 1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ .CONFIG_MAP_NAME }}
          env:
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .RDS_SECRET_NAME }}
                  key: username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .RDS_SECRET_NAME }}
                  key: password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .RDS_SECRET_NAME }}
                  key: default_db
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .RDS_SECRET_NAME }}
                  key: endpoint
            - name: MCLOUD_STORAGE_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .S3_SECRET_NAME }}
                  key: access_key_id
            - name: MCLOUD_STORAGE_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .S3_SECRET_NAME }}
                  key: secret_access_key
            - name: MCLOUD_STORAGE_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .S3_SECRET_NAME }}
                  key: name
