---
apiVersion: v1
kind: Service
metadata:
  name: {{ .JSARC_NAME }}
spec:
  selector:
    name: {{ .JSARC_NAME }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
