---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jsarc-admin
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx-external"
spec:
  tls:
    - hosts:
        - {{ .ADMIN_SITE_URL }}
      secretName: jsarcweb
  rules:
    - host: {{ .ADMIN_SITE_URL }}
      http:
        paths:
          - backend:
              serviceName: jsarc-admin
              servicePort: 8080
            path: /
