---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jsarc-prod
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    stable.k8s.psg.io/kcm.provider: "http"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/permanent-redirect-code: '301'
spec:
  tls:
    - hosts:
        - {{ .PROD_URL }}
      secretName: jsarcprod
  rules:
    - host: {{ .PROD_URL }}
      http:
        paths:
          - backend:
              serviceName: jsarc
              servicePort: 8080
            path: /

