apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jsarc
  labels:
    # @Note: specify label cert-manager.io/solver to specify that the route53 dns01 solver should be used
    cert-manager.io/solver: http01
spec:
  secretName: jsarcweb-cmio
  issuerRef:
    # use letsencrypt-staging while developing and testing your certificates
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - {{ .SITE_URL }}
