---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
    - name: mysql-client
      image: quay.io/ukhomeofficedigital/mysql:5.7.0
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
      env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: jsarc-prod-rds
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jsarc-prod-rds
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: jsarc-prod-rds
              key: default_db
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: jsarc-prod-rds
              key: endpoint
        - name: MYSQL_ROOT_PASSWORD
          value: tsrtsrtsrtfwafwadartsr

