# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7-apache-node-browsers-legacy

    working_directory: ~/repo

    steps:
    - run: echo 'No Tests'


  dockerise:
    docker:
    - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker

    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Setup aws cli
        command: sudo pip install awscli

    - run:
        name: Build container
        command: |
          aws ecr get-login --no-include-email | bash
          docker build -t $DOCKER_REPO/jsarcwordpress:$CIRCLE_BUILD_NUM .
          docker push $DOCKER_REPO/jsarcwordpress:$CIRCLE_BUILD_NUM
          echo "$DOCKER_REPO/jsarcwordpress:$CIRCLE_BUILD_NUM" > jsarcwordpress.txt
        environment:
          DOCKER_REPO: 721956817211.dkr.ecr.eu-west-1.amazonaws.com
    - persist_to_workspace:
        root: ./
        paths:
        - jsarcwordpress.txt

  deploy:
    docker:
    - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
    - checkout

    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Setup aws cli
        command: sudo pip install awscli

    - run:
        name: Deploy to ECS
        working_directory: jsarc-infra/
        command: |
          aws cloudformation update-stack \
          --stack-name ecs \
          --template-body file://ecs.yaml \
          --parameters ParameterKey=containerImage,ParameterValue="$(cat /tmp/workspace/jsarcwordpress.txt)"


workflows:
  version: 2
  build:
    jobs:
    - test
    - dockerise:
        context: jsarc
        filters:
          branches:
            only:
            - master
    - deploy:
        context: jsarc
        requires:
          - dockerise
        filters:
          branches:
            only:
              - master
